baseURL = 'https://zenithdrive.github.io/myblog'
languageCode = 'ja-ja'
title = 'ZenithDrive Blog'
theme = 'PaperMod'
publishDir = 'docs'

[params]
   ShowReadingTime = true
   ShowShareButtons = true
   ShowToc = true
   TocOpen = false
   defaultTheme = "auto"