baseURL = 'http://localhost:1313/'
languageCode = 'ja-ja'
title = 'ZenithDrive Blog'
theme = 'PaperMod'

[params]
   ShowReadingTime = true
   ShowShareButtons = true
   ShowToc = true
   TocOpen = false
   defaultTheme = "auto"
   publisherDir = "docs"