baseURL = 'https://zenithdrive.github.io/myblog/'
languageCode = 'ja-ja'
title = 'ZenithDrive Blog'
theme = 'hugo-clarity'
publishDir = 'public'
relativeURLs = true
canonifyURLs = true

[params]
	author = "ZenithDrive"
	description = "A blog about AI, technology, and self-drivng car"
	mainSections = ["posts"]
	showReadingTime = true